package persistencias;
// Generated 10-04-2018 08:51:26 AM by Hibernate Tools 4.3.1



/**
 * Compras generated by hbm2java
 */
public class Compras  implements java.io.Serializable {


     private Integer idCompra;
     private Productos productos;
     private Proveedores proveedores;
     private String NDocumento;
     private Integer cantidad;
     private Double monto;
     private String fechaCompra;
     private String estadoCompra;

    public Compras() {
    }

	
    public Compras(Productos productos, Proveedores proveedores, String NDocumento) {
        this.productos = productos;
        this.proveedores = proveedores;
        this.NDocumento = NDocumento;
    }
    public Compras(Productos productos, Proveedores proveedores, String NDocumento, Integer cantidad, Double monto, String fechaCompra, String estadoCompra) {
       this.productos = productos;
       this.proveedores = proveedores;
       this.NDocumento = NDocumento;
       this.cantidad = cantidad;
       this.monto = monto;
       this.fechaCompra = fechaCompra;
       this.estadoCompra = estadoCompra;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getNDocumento() {
        return this.NDocumento;
    }
    
    public void setNDocumento(String NDocumento) {
        this.NDocumento = NDocumento;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public String getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(String fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getEstadoCompra() {
        return this.estadoCompra;
    }
    
    public void setEstadoCompra(String estadoCompra) {
        this.estadoCompra = estadoCompra;
    }




}


