package persistencias;
// Generated 09-24-2018 10:53:31 AM by Hibernate Tools 4.3.1



/**
 * Compras generated by hbm2java
 */
public class Compras  implements java.io.Serializable {


     private Integer idCompra;
     private Productos productos;
     private Proveedores proveedores;
     private String nDocumento;
     private Integer cantidad;
     private Double monto;
     private String fechaCompra;

    public Compras() {
    }

	
    public Compras(Productos productos, Proveedores proveedores) {
        this.productos = productos;
        this.proveedores = proveedores;
    }
    public Compras(Productos productos, Proveedores proveedores, String nDocumento, Integer cantidad, Double monto, String fechaCompra) {
       this.productos = productos;
       this.proveedores = proveedores;
       this.nDocumento = nDocumento;
       this.cantidad = cantidad;
       this.monto = monto;
       this.fechaCompra = fechaCompra;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }

    public String getnDocumento() {
        return nDocumento;
    }

    public void setnDocumento(String nDocumento) {
        this.nDocumento = nDocumento;
    }
    
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public String getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(String fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

}


