package persistencias;
// Generated 09-04-2018 08:49:34 AM by Hibernate Tools 4.3.1



/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private Integer idFactura;
     private Sucursales sucursales;
     private Ventas ventas;
     private String fechaVenta;

    public Facturas() {
    }

	
    public Facturas(Sucursales sucursales, Ventas ventas) {
        this.sucursales = sucursales;
        this.ventas = ventas;
    }
    public Facturas(Sucursales sucursales, Ventas ventas, String fechaVenta) {
       this.sucursales = sucursales;
       this.ventas = ventas;
       this.fechaVenta = fechaVenta;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public String getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(String fechaVenta) {
        this.fechaVenta = fechaVenta;
    }




}


