package persistencias;
// Generated 09-25-2018 08:37:16 AM by Hibernate Tools 4.3.1



/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private Integer idFactura;
     private Sucursales sucursales;
     private Ventas ventas;
     private String NDocumento;
     private String fechaVenta;
     private String estadoFactura;

    public Facturas() {
    }

	
    public Facturas(Sucursales sucursales, Ventas ventas, String NDocumento) {
        this.sucursales = sucursales;
        this.ventas = ventas;
        this.NDocumento = NDocumento;
    }
    public Facturas(Sucursales sucursales, Ventas ventas, String NDocumento, String fechaVenta, String estadoFactura) {
       this.sucursales = sucursales;
       this.ventas = ventas;
       this.NDocumento = NDocumento;
       this.fechaVenta = fechaVenta;
       this.estadoFactura = estadoFactura;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public String getNDocumento() {
        return this.NDocumento;
    }
    
    public void setNDocumento(String NDocumento) {
        this.NDocumento = NDocumento;
    }
    public String getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(String fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getEstadoFactura() {
        return this.estadoFactura;
    }
    
    public void setEstadoFactura(String estadoFactura) {
        this.estadoFactura = estadoFactura;
    }




}


