package persistencias;
// Generated 09-04-2018 08:49:34 AM by Hibernate Tools 4.3.1



/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private Integer idInventario;
     private Productos productos;
     private Proveedores proveedores;
     private Sucursales sucursales;
     private Integer cant;
     private Integer stock;
     private String estado;

    public Inventario() {
    }

	
    public Inventario(Productos productos, Proveedores proveedores, Sucursales sucursales) {
        this.productos = productos;
        this.proveedores = proveedores;
        this.sucursales = sucursales;
    }
    public Inventario(Productos productos, Proveedores proveedores, Sucursales sucursales, Integer cant, Integer stock, String estado) {
       this.productos = productos;
       this.proveedores = proveedores;
       this.sucursales = sucursales;
       this.cant = cant;
       this.stock = stock;
       this.estado = estado;
    }
   
    public Integer getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(Integer idInventario) {
        this.idInventario = idInventario;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Integer getCant() {
        return this.cant;
    }
    
    public void setCant(Integer cant) {
        this.cant = cant;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


