package persistencias;
// Generated 10-04-2018 08:51:26 AM by Hibernate Tools 4.3.1



/**
 * Monedas generated by hbm2java
 */
public class Monedas  implements java.io.Serializable {


     private Integer idMoneda;
     private String moneda;
     private String simbolo;
     private Double equivalencia;
     private String equivalente;

    public Monedas() {
    }

	
    public Monedas(String moneda, String simbolo) {
        this.moneda = moneda;
        this.simbolo = simbolo;
    }
    public Monedas(String moneda, String simbolo, Double equivalencia, String equivalente) {
       this.moneda = moneda;
       this.simbolo = simbolo;
       this.equivalencia = equivalencia;
       this.equivalente = equivalente;
    }
   
    public Integer getIdMoneda() {
        return this.idMoneda;
    }
    
    public void setIdMoneda(Integer idMoneda) {
        this.idMoneda = idMoneda;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public String getSimbolo() {
        return this.simbolo;
    }
    
    public void setSimbolo(String simbolo) {
        this.simbolo = simbolo;
    }
    public Double getEquivalencia() {
        return this.equivalencia;
    }
    
    public void setEquivalencia(Double equivalencia) {
        this.equivalencia = equivalencia;
    }
    public String getEquivalente() {
        return this.equivalente;
    }
    
    public void setEquivalente(String equivalente) {
        this.equivalente = equivalente;
    }




}


