package persistencias;
// Generated 09-25-2018 08:37:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Fabricantes fabricantes;
     private Proveedores proveedores;
     private String producto;
     private Set inventarios = new HashSet(0);
     private Set comprases = new HashSet(0);
     private Set ventases = new HashSet(0);

    public Productos() {
    }

	
    public Productos(Fabricantes fabricantes, Proveedores proveedores) {
        this.fabricantes = fabricantes;
        this.proveedores = proveedores;
    }
    public Productos(Fabricantes fabricantes, Proveedores proveedores, String producto, Set inventarios, Set comprases, Set ventases) {
       this.fabricantes = fabricantes;
       this.proveedores = proveedores;
       this.producto = producto;
       this.inventarios = inventarios;
       this.comprases = comprases;
       this.ventases = ventases;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Fabricantes getFabricantes() {
        return this.fabricantes;
    }
    
    public void setFabricantes(Fabricantes fabricantes) {
        this.fabricantes = fabricantes;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }




}


