package persistencias;
// Generated 09-25-2018 08:37:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private Integer idProveedor;
     private String proveedor;
     private String rubro;
     private String contacto;
     private String telefono;
     private Set inventarios = new HashSet(0);
     private Set productoses = new HashSet(0);
     private Set comprases = new HashSet(0);

    public Proveedores() {
    }

    public Proveedores(String proveedor, String rubro, String contacto, String telefono, Set inventarios, Set productoses, Set comprases) {
       this.proveedor = proveedor;
       this.rubro = rubro;
       this.contacto = contacto;
       this.telefono = telefono;
       this.inventarios = inventarios;
       this.productoses = productoses;
       this.comprases = comprases;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }
    public String getRubro() {
        return this.rubro;
    }
    
    public void setRubro(String rubro) {
        this.rubro = rubro;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }




}


