package persistencias;
// Generated 09-04-2018 08:49:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer idVenta;
     private Clientes clientes;
     private Productos productos;
     private Usuario usuario;
     private Integer cantidad;
     private Double monto;
     private String fechaVenta;
     private Sucursales sucursales;
     private Inventario inventario;
     private Set facturases = new HashSet(0);

    public Ventas() {
    }

	
    public Ventas(Clientes clientes, Productos productos, Usuario usuario, Sucursales sucursales, Inventario inventario) {
        this.clientes = clientes;
        this.productos = productos;
        this.usuario = usuario;
        this.sucursales = sucursales;
        this.inventario = inventario;
    }
    public Ventas(Clientes clientes, Productos productos, Usuario usuario, Integer cantidad, Double monto, String fechaVenta, Sucursales sucursales, Inventario inventario, Set facturases) {
       this.clientes = clientes;
       this.productos = productos;
       this.usuario = usuario;
       this.cantidad = cantidad;
       this.monto = monto;
       this.fechaVenta = fechaVenta;
       this.sucursales = sucursales;
       this.inventario = inventario;
       this.facturases = facturases;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }

    public String getFechaVenta() {
        return fechaVenta;
    }

    public void setFechaVenta(String fechaVenta) {
        this.fechaVenta = fechaVenta;
    }

    public Sucursales getSucursales() {
        return sucursales;
    }

    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }

    public Inventario getInventario() {
        return inventario;
    }

    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }

}
