package persistencias;
// Generated 10-04-2018 08:51:26 AM by Hibernate Tools 4.3.1



/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer idVenta;
     private Clientes clientes;
     private Inventario inventario;
     private Productos productos;
     private Sucursales sucursales;
     private Usuario usuario;
     private String NDocumento;
     private Integer cantidad;
     private Double monto;
     private String fechaVenta;
     private String estadoVenta;

    public Ventas() {
    }

	
    public Ventas(Clientes clientes, Inventario inventario, Productos productos, Sucursales sucursales, Usuario usuario, String NDocumento) {
        this.clientes = clientes;
        this.inventario = inventario;
        this.productos = productos;
        this.sucursales = sucursales;
        this.usuario = usuario;
        this.NDocumento = NDocumento;
    }
    public Ventas(Clientes clientes, Inventario inventario, Productos productos, Sucursales sucursales, Usuario usuario, String NDocumento, Integer cantidad, Double monto, String fechaVenta, String estadoVenta) {
       this.clientes = clientes;
       this.inventario = inventario;
       this.productos = productos;
       this.sucursales = sucursales;
       this.usuario = usuario;
       this.NDocumento = NDocumento;
       this.cantidad = cantidad;
       this.monto = monto;
       this.fechaVenta = fechaVenta;
       this.estadoVenta = estadoVenta;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNDocumento() {
        return this.NDocumento;
    }
    
    public void setNDocumento(String NDocumento) {
        this.NDocumento = NDocumento;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public String getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(String fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getEstadoVenta() {
        return this.estadoVenta;
    }
    
    public void setEstadoVenta(String estadoVenta) {
        this.estadoVenta = estadoVenta;
    }




}


